return {
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  lazy = true,
  cmd = {
    "MasonToolsClean",
    "MasonToolsInstall",
    "MasonToolsInstallSync",
    "MasonToolsUpdate",
    "MasonToolsUpdateSync",
  },
  opts = {
    ensure_installed = {
      "black",
      "isort",
      "prettier",
      "prettierd",
      "stylua",
      "shfmt",
      "hclfmt",
      "mdformat",
      "yamlfmt",
      "jq",
      -- language servers
      "ansiblels",
      "awk_ls",
      "bashls",
      "cssls",
      "dockerls",
      "gopls",
      "groovyls",
      "helm_ls",
      "html",
      "jsonls",
      "lua_ls",
      "marksman",
      "pyright",
      "terraformls",
      "vimls",
      "yamlls",
    },
  },
  dependencies = {
    "mason-org/mason.nvim",
    "mason-org/mason-lspconfig.nvim",
  },
}
