return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  lazy = false,
  build = ":TSUpdate",
  config = function()
    require("nvim-treesitter").setup({})

    -- v1 main branch only installs parsers; we must enable highlighting ourselves.
    vim.api.nvim_create_autocmd("FileType", {
      pattern = "*",
      callback = function(args)
        pcall(vim.treesitter.start, args.buf)
      end,
    })

    require("nvim-treesitter").install({
      "awk",
      "bash",
      "css",
      "csv",
      "diff",
      "dockerfile",
      "dtd",
      "editorconfig",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "goctl",
      "gomod",
      "gosum",
      "gotmpl",
      "gowork",
      "gpg",
      "groovy",
      "hcl",
      "helm",
      "hjson",
      "html",
      "http",
      "java",
      "javascript",
      "jq",
      "json",
      "json5",
      "jsonnet",
      "kotlin",
      "lua",
      "luadoc",
      "make",
      "markdown",
      "markdown_inline",
      "nginx",
      "passwd",
      "php",
      "php_only",
      "phpdoc",
      "printf",
      "promql",
      "properties",
      "python",
      "regex",
      "sql",
      "ssh_config",
      "strace",
      "terraform",
      "tmux",
      "toml",
      "tsv",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    })
  end,
}

